name: interface_viewer
description: A new Flutter project

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.2.0
  http: ^1.2.2        # ‚Üê TAMBAH INI

flutter:
  uses-material-design: true
  assets:
    - assets/LogoBRIN.png
